### ISSUE TITLE
Action cannot find go file

### ISSUE THREAD

**Issue by xiongchiamiov** [mnmandahalf/check-ecr-image-exists#1]
When I run this action, I get this error:

```
stat ecr.go: no such file or directory
```

It looks like that file, and possibly the other golang files, needs to be `COPY`ed in the Dockerfile.

**Comment by mnmandahalf** [comment]
@xiongchiamiov
Thank you for your report.
This problem is solved in commits below.
https://github.com/mnmandahalf/github-actions-check-ecr-image-exists/compare/v0.1.0...v0.1.1
